name: Team awesome's approval workflow
on: pull_request_review
jobs:
  labelWhenApproved:
    runs-on: ubuntu-latest
    steps:
      - name: Label approved pull requests
        uses: abinoda/label-when-approved-action@1.0.5
        env:
          APPROVALS: "2"
          ADD_LABEL: "approved"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
